version: '3.9'

services:
  apache:
    container_name: 'apache'
    image: apache:latest
    build:
      context: ./apache/
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./apache/httpd.conf:/etc/apache2/httpd.conf
    networks:
      - r-proxy
  webapp:
    container_name: 'webapp'
    build:
      context: .
      args:
        PUBLIC_SUPABASE_URL: $PUBLIC_SUPABASE_URL
        PUBLIC_SUPABASE_ANON_KEY: $PUBLIC_SUPABASE_ANON_KEY
    restart: unless-stopped
    networks:
      - r-proxy
    env_file:
      - .env

networks:
  r-proxy:
    driver: bridge
